/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"
	scheme "kubeform.dev/provider-equinixmetal-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProjectAPIKeysGetter has a method to return a ProjectAPIKeyInterface.
// A group's client should implement this interface.
type ProjectAPIKeysGetter interface {
	ProjectAPIKeys(namespace string) ProjectAPIKeyInterface
}

// ProjectAPIKeyInterface has methods to work with ProjectAPIKey resources.
type ProjectAPIKeyInterface interface {
	Create(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.CreateOptions) (*v1alpha1.ProjectAPIKey, error)
	Update(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (*v1alpha1.ProjectAPIKey, error)
	UpdateStatus(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (*v1alpha1.ProjectAPIKey, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ProjectAPIKey, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ProjectAPIKeyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectAPIKey, err error)
	ProjectAPIKeyExpansion
}

// projectAPIKeys implements ProjectAPIKeyInterface
type projectAPIKeys struct {
	client rest.Interface
	ns     string
}

// newProjectAPIKeys returns a ProjectAPIKeys
func newProjectAPIKeys(c *MetalV1alpha1Client, namespace string) *projectAPIKeys {
	return &projectAPIKeys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the projectAPIKey, and returns the corresponding projectAPIKey object, and an error if there is any.
func (c *projectAPIKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	result = &v1alpha1.ProjectAPIKey{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectapikeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProjectAPIKeys that match those selectors.
func (c *projectAPIKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectAPIKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ProjectAPIKeyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested projectAPIKeys.
func (c *projectAPIKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("projectapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a projectAPIKey and creates it.  Returns the server's representation of the projectAPIKey, and an error, if there is any.
func (c *projectAPIKeys) Create(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.CreateOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	result = &v1alpha1.ProjectAPIKey{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("projectapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectAPIKey).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a projectAPIKey and updates it. Returns the server's representation of the projectAPIKey, and an error, if there is any.
func (c *projectAPIKeys) Update(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	result = &v1alpha1.ProjectAPIKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectapikeys").
		Name(projectAPIKey.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectAPIKey).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *projectAPIKeys) UpdateStatus(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	result = &v1alpha1.ProjectAPIKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectapikeys").
		Name(projectAPIKey.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectAPIKey).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the projectAPIKey and deletes it. Returns an error if one occurs.
func (c *projectAPIKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectapikeys").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *projectAPIKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectapikeys").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched projectAPIKey.
func (c *projectAPIKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectAPIKey, err error) {
	result = &v1alpha1.ProjectAPIKey{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("projectapikeys").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
