/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"
	scheme "kubeform.dev/provider-equinixmetal-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProjectSSHKeysGetter has a method to return a ProjectSSHKeyInterface.
// A group's client should implement this interface.
type ProjectSSHKeysGetter interface {
	ProjectSSHKeys(namespace string) ProjectSSHKeyInterface
}

// ProjectSSHKeyInterface has methods to work with ProjectSSHKey resources.
type ProjectSSHKeyInterface interface {
	Create(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.CreateOptions) (*v1alpha1.ProjectSSHKey, error)
	Update(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (*v1alpha1.ProjectSSHKey, error)
	UpdateStatus(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (*v1alpha1.ProjectSSHKey, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ProjectSSHKey, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ProjectSSHKeyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectSSHKey, err error)
	ProjectSSHKeyExpansion
}

// projectSSHKeys implements ProjectSSHKeyInterface
type projectSSHKeys struct {
	client rest.Interface
	ns     string
}

// newProjectSSHKeys returns a ProjectSSHKeys
func newProjectSSHKeys(c *MetalV1alpha1Client, namespace string) *projectSSHKeys {
	return &projectSSHKeys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the projectSSHKey, and returns the corresponding projectSSHKey object, and an error if there is any.
func (c *projectSSHKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	result = &v1alpha1.ProjectSSHKey{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectsshkeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProjectSSHKeys that match those selectors.
func (c *projectSSHKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectSSHKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ProjectSSHKeyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectsshkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested projectSSHKeys.
func (c *projectSSHKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("projectsshkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a projectSSHKey and creates it.  Returns the server's representation of the projectSSHKey, and an error, if there is any.
func (c *projectSSHKeys) Create(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.CreateOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	result = &v1alpha1.ProjectSSHKey{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("projectsshkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectSSHKey).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a projectSSHKey and updates it. Returns the server's representation of the projectSSHKey, and an error, if there is any.
func (c *projectSSHKeys) Update(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	result = &v1alpha1.ProjectSSHKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectsshkeys").
		Name(projectSSHKey.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectSSHKey).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *projectSSHKeys) UpdateStatus(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	result = &v1alpha1.ProjectSSHKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectsshkeys").
		Name(projectSSHKey.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectSSHKey).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the projectSSHKey and deletes it. Returns an error if one occurs.
func (c *projectSSHKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectsshkeys").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *projectSSHKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectsshkeys").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched projectSSHKey.
func (c *projectSSHKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectSSHKey, err error) {
	result = &v1alpha1.ProjectSSHKey{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("projectsshkeys").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
