/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BgpSessionListerExpansion allows custom methods to be added to
// BgpSessionLister.
type BgpSessionListerExpansion interface{}

// BgpSessionNamespaceListerExpansion allows custom methods to be added to
// BgpSessionNamespaceLister.
type BgpSessionNamespaceListerExpansion interface{}

// ConnectionListerExpansion allows custom methods to be added to
// ConnectionLister.
type ConnectionListerExpansion interface{}

// ConnectionNamespaceListerExpansion allows custom methods to be added to
// ConnectionNamespaceLister.
type ConnectionNamespaceListerExpansion interface{}

// DeviceListerExpansion allows custom methods to be added to
// DeviceLister.
type DeviceListerExpansion interface{}

// DeviceNamespaceListerExpansion allows custom methods to be added to
// DeviceNamespaceLister.
type DeviceNamespaceListerExpansion interface{}

// DeviceNetworkTypeListerExpansion allows custom methods to be added to
// DeviceNetworkTypeLister.
type DeviceNetworkTypeListerExpansion interface{}

// DeviceNetworkTypeNamespaceListerExpansion allows custom methods to be added to
// DeviceNetworkTypeNamespaceLister.
type DeviceNetworkTypeNamespaceListerExpansion interface{}

// IpAttachmentListerExpansion allows custom methods to be added to
// IpAttachmentLister.
type IpAttachmentListerExpansion interface{}

// IpAttachmentNamespaceListerExpansion allows custom methods to be added to
// IpAttachmentNamespaceLister.
type IpAttachmentNamespaceListerExpansion interface{}

// OrganizationListerExpansion allows custom methods to be added to
// OrganizationLister.
type OrganizationListerExpansion interface{}

// OrganizationNamespaceListerExpansion allows custom methods to be added to
// OrganizationNamespaceLister.
type OrganizationNamespaceListerExpansion interface{}

// PortVLANAttachmentListerExpansion allows custom methods to be added to
// PortVLANAttachmentLister.
type PortVLANAttachmentListerExpansion interface{}

// PortVLANAttachmentNamespaceListerExpansion allows custom methods to be added to
// PortVLANAttachmentNamespaceLister.
type PortVLANAttachmentNamespaceListerExpansion interface{}

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// ProjectNamespaceListerExpansion allows custom methods to be added to
// ProjectNamespaceLister.
type ProjectNamespaceListerExpansion interface{}

// ProjectAPIKeyListerExpansion allows custom methods to be added to
// ProjectAPIKeyLister.
type ProjectAPIKeyListerExpansion interface{}

// ProjectAPIKeyNamespaceListerExpansion allows custom methods to be added to
// ProjectAPIKeyNamespaceLister.
type ProjectAPIKeyNamespaceListerExpansion interface{}

// ProjectSSHKeyListerExpansion allows custom methods to be added to
// ProjectSSHKeyLister.
type ProjectSSHKeyListerExpansion interface{}

// ProjectSSHKeyNamespaceListerExpansion allows custom methods to be added to
// ProjectSSHKeyNamespaceLister.
type ProjectSSHKeyNamespaceListerExpansion interface{}

// ReservedIPBlockListerExpansion allows custom methods to be added to
// ReservedIPBlockLister.
type ReservedIPBlockListerExpansion interface{}

// ReservedIPBlockNamespaceListerExpansion allows custom methods to be added to
// ReservedIPBlockNamespaceLister.
type ReservedIPBlockNamespaceListerExpansion interface{}

// SpotMarketRequestListerExpansion allows custom methods to be added to
// SpotMarketRequestLister.
type SpotMarketRequestListerExpansion interface{}

// SpotMarketRequestNamespaceListerExpansion allows custom methods to be added to
// SpotMarketRequestNamespaceLister.
type SpotMarketRequestNamespaceListerExpansion interface{}

// SshKeyListerExpansion allows custom methods to be added to
// SshKeyLister.
type SshKeyListerExpansion interface{}

// SshKeyNamespaceListerExpansion allows custom methods to be added to
// SshKeyNamespaceLister.
type SshKeyNamespaceListerExpansion interface{}

// UserAPIKeyListerExpansion allows custom methods to be added to
// UserAPIKeyLister.
type UserAPIKeyListerExpansion interface{}

// UserAPIKeyNamespaceListerExpansion allows custom methods to be added to
// UserAPIKeyNamespaceLister.
type UserAPIKeyNamespaceListerExpansion interface{}

// VirtualCircuitListerExpansion allows custom methods to be added to
// VirtualCircuitLister.
type VirtualCircuitListerExpansion interface{}

// VirtualCircuitNamespaceListerExpansion allows custom methods to be added to
// VirtualCircuitNamespaceLister.
type VirtualCircuitNamespaceListerExpansion interface{}

// VlanListerExpansion allows custom methods to be added to
// VlanLister.
type VlanListerExpansion interface{}

// VlanNamespaceListerExpansion allows custom methods to be added to
// VlanNamespaceLister.
type VlanNamespaceListerExpansion interface{}

// VolumeListerExpansion allows custom methods to be added to
// VolumeLister.
type VolumeListerExpansion interface{}

// VolumeNamespaceListerExpansion allows custom methods to be added to
// VolumeNamespaceLister.
type VolumeNamespaceListerExpansion interface{}

// VolumeAttachmentListerExpansion allows custom methods to be added to
// VolumeAttachmentLister.
type VolumeAttachmentListerExpansion interface{}

// VolumeAttachmentNamespaceListerExpansion allows custom methods to be added to
// VolumeAttachmentNamespaceLister.
type VolumeAttachmentNamespaceListerExpansion interface{}
