/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/port/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVlanAttachments implements VlanAttachmentInterface
type FakeVlanAttachments struct {
	Fake *FakePortV1alpha1
	ns   string
}

var vlanattachmentsResource = schema.GroupVersionResource{Group: "port.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "vlanattachments"}

var vlanattachmentsKind = schema.GroupVersionKind{Group: "port.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "VlanAttachment"}

// Get takes name of the vlanAttachment, and returns the corresponding vlanAttachment object, and an error if there is any.
func (c *FakeVlanAttachments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VlanAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vlanattachmentsResource, c.ns, name), &v1alpha1.VlanAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VlanAttachment), err
}

// List takes label and field selectors, and returns the list of VlanAttachments that match those selectors.
func (c *FakeVlanAttachments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VlanAttachmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vlanattachmentsResource, vlanattachmentsKind, c.ns, opts), &v1alpha1.VlanAttachmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VlanAttachmentList{ListMeta: obj.(*v1alpha1.VlanAttachmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.VlanAttachmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vlanAttachments.
func (c *FakeVlanAttachments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vlanattachmentsResource, c.ns, opts))

}

// Create takes the representation of a vlanAttachment and creates it.  Returns the server's representation of the vlanAttachment, and an error, if there is any.
func (c *FakeVlanAttachments) Create(ctx context.Context, vlanAttachment *v1alpha1.VlanAttachment, opts v1.CreateOptions) (result *v1alpha1.VlanAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vlanattachmentsResource, c.ns, vlanAttachment), &v1alpha1.VlanAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VlanAttachment), err
}

// Update takes the representation of a vlanAttachment and updates it. Returns the server's representation of the vlanAttachment, and an error, if there is any.
func (c *FakeVlanAttachments) Update(ctx context.Context, vlanAttachment *v1alpha1.VlanAttachment, opts v1.UpdateOptions) (result *v1alpha1.VlanAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vlanattachmentsResource, c.ns, vlanAttachment), &v1alpha1.VlanAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VlanAttachment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVlanAttachments) UpdateStatus(ctx context.Context, vlanAttachment *v1alpha1.VlanAttachment, opts v1.UpdateOptions) (*v1alpha1.VlanAttachment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vlanattachmentsResource, "status", c.ns, vlanAttachment), &v1alpha1.VlanAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VlanAttachment), err
}

// Delete takes name of the vlanAttachment and deletes it. Returns an error if one occurs.
func (c *FakeVlanAttachments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vlanattachmentsResource, c.ns, name), &v1alpha1.VlanAttachment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVlanAttachments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vlanattachmentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VlanAttachmentList{})
	return err
}

// Patch applies the patch and returns the patched vlanAttachment.
func (c *FakeVlanAttachments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VlanAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vlanattachmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VlanAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VlanAttachment), err
}
