/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBgpSessions implements BgpSessionInterface
type FakeBgpSessions struct {
	Fake *FakeMetalV1alpha1
	ns   string
}

var bgpsessionsResource = schema.GroupVersionResource{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "bgpsessions"}

var bgpsessionsKind = schema.GroupVersionKind{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "BgpSession"}

// Get takes name of the bgpSession, and returns the corresponding bgpSession object, and an error if there is any.
func (c *FakeBgpSessions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BgpSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bgpsessionsResource, c.ns, name), &v1alpha1.BgpSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BgpSession), err
}

// List takes label and field selectors, and returns the list of BgpSessions that match those selectors.
func (c *FakeBgpSessions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BgpSessionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bgpsessionsResource, bgpsessionsKind, c.ns, opts), &v1alpha1.BgpSessionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BgpSessionList{ListMeta: obj.(*v1alpha1.BgpSessionList).ListMeta}
	for _, item := range obj.(*v1alpha1.BgpSessionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bgpSessions.
func (c *FakeBgpSessions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bgpsessionsResource, c.ns, opts))

}

// Create takes the representation of a bgpSession and creates it.  Returns the server's representation of the bgpSession, and an error, if there is any.
func (c *FakeBgpSessions) Create(ctx context.Context, bgpSession *v1alpha1.BgpSession, opts v1.CreateOptions) (result *v1alpha1.BgpSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bgpsessionsResource, c.ns, bgpSession), &v1alpha1.BgpSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BgpSession), err
}

// Update takes the representation of a bgpSession and updates it. Returns the server's representation of the bgpSession, and an error, if there is any.
func (c *FakeBgpSessions) Update(ctx context.Context, bgpSession *v1alpha1.BgpSession, opts v1.UpdateOptions) (result *v1alpha1.BgpSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bgpsessionsResource, c.ns, bgpSession), &v1alpha1.BgpSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BgpSession), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBgpSessions) UpdateStatus(ctx context.Context, bgpSession *v1alpha1.BgpSession, opts v1.UpdateOptions) (*v1alpha1.BgpSession, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bgpsessionsResource, "status", c.ns, bgpSession), &v1alpha1.BgpSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BgpSession), err
}

// Delete takes name of the bgpSession and deletes it. Returns an error if one occurs.
func (c *FakeBgpSessions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bgpsessionsResource, c.ns, name), &v1alpha1.BgpSession{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBgpSessions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bgpsessionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BgpSessionList{})
	return err
}

// Patch applies the patch and returns the patched bgpSession.
func (c *FakeBgpSessions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BgpSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bgpsessionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BgpSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BgpSession), err
}
