/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePortVLANAttachments implements PortVLANAttachmentInterface
type FakePortVLANAttachments struct {
	Fake *FakeMetalV1alpha1
	ns   string
}

var portvlanattachmentsResource = schema.GroupVersionResource{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "portvlanattachments"}

var portvlanattachmentsKind = schema.GroupVersionKind{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "PortVLANAttachment"}

// Get takes name of the portVLANAttachment, and returns the corresponding portVLANAttachment object, and an error if there is any.
func (c *FakePortVLANAttachments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PortVLANAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(portvlanattachmentsResource, c.ns, name), &v1alpha1.PortVLANAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortVLANAttachment), err
}

// List takes label and field selectors, and returns the list of PortVLANAttachments that match those selectors.
func (c *FakePortVLANAttachments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PortVLANAttachmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(portvlanattachmentsResource, portvlanattachmentsKind, c.ns, opts), &v1alpha1.PortVLANAttachmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PortVLANAttachmentList{ListMeta: obj.(*v1alpha1.PortVLANAttachmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.PortVLANAttachmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested portVLANAttachments.
func (c *FakePortVLANAttachments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(portvlanattachmentsResource, c.ns, opts))

}

// Create takes the representation of a portVLANAttachment and creates it.  Returns the server's representation of the portVLANAttachment, and an error, if there is any.
func (c *FakePortVLANAttachments) Create(ctx context.Context, portVLANAttachment *v1alpha1.PortVLANAttachment, opts v1.CreateOptions) (result *v1alpha1.PortVLANAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(portvlanattachmentsResource, c.ns, portVLANAttachment), &v1alpha1.PortVLANAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortVLANAttachment), err
}

// Update takes the representation of a portVLANAttachment and updates it. Returns the server's representation of the portVLANAttachment, and an error, if there is any.
func (c *FakePortVLANAttachments) Update(ctx context.Context, portVLANAttachment *v1alpha1.PortVLANAttachment, opts v1.UpdateOptions) (result *v1alpha1.PortVLANAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(portvlanattachmentsResource, c.ns, portVLANAttachment), &v1alpha1.PortVLANAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortVLANAttachment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePortVLANAttachments) UpdateStatus(ctx context.Context, portVLANAttachment *v1alpha1.PortVLANAttachment, opts v1.UpdateOptions) (*v1alpha1.PortVLANAttachment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(portvlanattachmentsResource, "status", c.ns, portVLANAttachment), &v1alpha1.PortVLANAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortVLANAttachment), err
}

// Delete takes name of the portVLANAttachment and deletes it. Returns an error if one occurs.
func (c *FakePortVLANAttachments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(portvlanattachmentsResource, c.ns, name), &v1alpha1.PortVLANAttachment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePortVLANAttachments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(portvlanattachmentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PortVLANAttachmentList{})
	return err
}

// Patch applies the patch and returns the patched portVLANAttachment.
func (c *FakePortVLANAttachments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PortVLANAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(portvlanattachmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PortVLANAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortVLANAttachment), err
}
