/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualCircuits implements VirtualCircuitInterface
type FakeVirtualCircuits struct {
	Fake *FakeMetalV1alpha1
	ns   string
}

var virtualcircuitsResource = schema.GroupVersionResource{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "virtualcircuits"}

var virtualcircuitsKind = schema.GroupVersionKind{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "VirtualCircuit"}

// Get takes name of the virtualCircuit, and returns the corresponding virtualCircuit object, and an error if there is any.
func (c *FakeVirtualCircuits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualCircuit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualcircuitsResource, c.ns, name), &v1alpha1.VirtualCircuit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualCircuit), err
}

// List takes label and field selectors, and returns the list of VirtualCircuits that match those selectors.
func (c *FakeVirtualCircuits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualCircuitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualcircuitsResource, virtualcircuitsKind, c.ns, opts), &v1alpha1.VirtualCircuitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualCircuitList{ListMeta: obj.(*v1alpha1.VirtualCircuitList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualCircuitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualCircuits.
func (c *FakeVirtualCircuits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualcircuitsResource, c.ns, opts))

}

// Create takes the representation of a virtualCircuit and creates it.  Returns the server's representation of the virtualCircuit, and an error, if there is any.
func (c *FakeVirtualCircuits) Create(ctx context.Context, virtualCircuit *v1alpha1.VirtualCircuit, opts v1.CreateOptions) (result *v1alpha1.VirtualCircuit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualcircuitsResource, c.ns, virtualCircuit), &v1alpha1.VirtualCircuit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualCircuit), err
}

// Update takes the representation of a virtualCircuit and updates it. Returns the server's representation of the virtualCircuit, and an error, if there is any.
func (c *FakeVirtualCircuits) Update(ctx context.Context, virtualCircuit *v1alpha1.VirtualCircuit, opts v1.UpdateOptions) (result *v1alpha1.VirtualCircuit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualcircuitsResource, c.ns, virtualCircuit), &v1alpha1.VirtualCircuit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualCircuit), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualCircuits) UpdateStatus(ctx context.Context, virtualCircuit *v1alpha1.VirtualCircuit, opts v1.UpdateOptions) (*v1alpha1.VirtualCircuit, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualcircuitsResource, "status", c.ns, virtualCircuit), &v1alpha1.VirtualCircuit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualCircuit), err
}

// Delete takes name of the virtualCircuit and deletes it. Returns an error if one occurs.
func (c *FakeVirtualCircuits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualcircuitsResource, c.ns, name), &v1alpha1.VirtualCircuit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualCircuits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualcircuitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualCircuitList{})
	return err
}

// Patch applies the patch and returns the patched virtualCircuit.
func (c *FakeVirtualCircuits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualCircuit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualcircuitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualCircuit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualCircuit), err
}
