/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectAPIKeys implements ProjectAPIKeyInterface
type FakeProjectAPIKeys struct {
	Fake *FakeMetalV1alpha1
	ns   string
}

var projectapikeysResource = schema.GroupVersionResource{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "projectapikeys"}

var projectapikeysKind = schema.GroupVersionKind{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "ProjectAPIKey"}

// Get takes name of the projectAPIKey, and returns the corresponding projectAPIKey object, and an error if there is any.
func (c *FakeProjectAPIKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectapikeysResource, c.ns, name), &v1alpha1.ProjectAPIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectAPIKey), err
}

// List takes label and field selectors, and returns the list of ProjectAPIKeys that match those selectors.
func (c *FakeProjectAPIKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectAPIKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectapikeysResource, projectapikeysKind, c.ns, opts), &v1alpha1.ProjectAPIKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectAPIKeyList{ListMeta: obj.(*v1alpha1.ProjectAPIKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectAPIKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectAPIKeys.
func (c *FakeProjectAPIKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectapikeysResource, c.ns, opts))

}

// Create takes the representation of a projectAPIKey and creates it.  Returns the server's representation of the projectAPIKey, and an error, if there is any.
func (c *FakeProjectAPIKeys) Create(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.CreateOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectapikeysResource, c.ns, projectAPIKey), &v1alpha1.ProjectAPIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectAPIKey), err
}

// Update takes the representation of a projectAPIKey and updates it. Returns the server's representation of the projectAPIKey, and an error, if there is any.
func (c *FakeProjectAPIKeys) Update(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectAPIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectapikeysResource, c.ns, projectAPIKey), &v1alpha1.ProjectAPIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectAPIKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectAPIKeys) UpdateStatus(ctx context.Context, projectAPIKey *v1alpha1.ProjectAPIKey, opts v1.UpdateOptions) (*v1alpha1.ProjectAPIKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectapikeysResource, "status", c.ns, projectAPIKey), &v1alpha1.ProjectAPIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectAPIKey), err
}

// Delete takes name of the projectAPIKey and deletes it. Returns an error if one occurs.
func (c *FakeProjectAPIKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectapikeysResource, c.ns, name), &v1alpha1.ProjectAPIKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectAPIKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectapikeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectAPIKeyList{})
	return err
}

// Patch applies the patch and returns the patched projectAPIKey.
func (c *FakeProjectAPIKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectAPIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectapikeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectAPIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectAPIKey), err
}
