/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/metal/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectSSHKeys implements ProjectSSHKeyInterface
type FakeProjectSSHKeys struct {
	Fake *FakeMetalV1alpha1
	ns   string
}

var projectsshkeysResource = schema.GroupVersionResource{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Resource: "projectsshkeys"}

var projectsshkeysKind = schema.GroupVersionKind{Group: "metal.equinixmetal.kubeform.com", Version: "v1alpha1", Kind: "ProjectSSHKey"}

// Get takes name of the projectSSHKey, and returns the corresponding projectSSHKey object, and an error if there is any.
func (c *FakeProjectSSHKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectsshkeysResource, c.ns, name), &v1alpha1.ProjectSSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSSHKey), err
}

// List takes label and field selectors, and returns the list of ProjectSSHKeys that match those selectors.
func (c *FakeProjectSSHKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectSSHKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectsshkeysResource, projectsshkeysKind, c.ns, opts), &v1alpha1.ProjectSSHKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectSSHKeyList{ListMeta: obj.(*v1alpha1.ProjectSSHKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectSSHKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectSSHKeys.
func (c *FakeProjectSSHKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectsshkeysResource, c.ns, opts))

}

// Create takes the representation of a projectSSHKey and creates it.  Returns the server's representation of the projectSSHKey, and an error, if there is any.
func (c *FakeProjectSSHKeys) Create(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.CreateOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectsshkeysResource, c.ns, projectSSHKey), &v1alpha1.ProjectSSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSSHKey), err
}

// Update takes the representation of a projectSSHKey and updates it. Returns the server's representation of the projectSSHKey, and an error, if there is any.
func (c *FakeProjectSSHKeys) Update(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (result *v1alpha1.ProjectSSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectsshkeysResource, c.ns, projectSSHKey), &v1alpha1.ProjectSSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSSHKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectSSHKeys) UpdateStatus(ctx context.Context, projectSSHKey *v1alpha1.ProjectSSHKey, opts v1.UpdateOptions) (*v1alpha1.ProjectSSHKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectsshkeysResource, "status", c.ns, projectSSHKey), &v1alpha1.ProjectSSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSSHKey), err
}

// Delete takes name of the projectSSHKey and deletes it. Returns an error if one occurs.
func (c *FakeProjectSSHKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectsshkeysResource, c.ns, name), &v1alpha1.ProjectSSHKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectSSHKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectsshkeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectSSHKeyList{})
	return err
}

// Patch applies the patch and returns the patched projectSSHKey.
func (c *FakeProjectSSHKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectSSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectsshkeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectSSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSSHKey), err
}
