/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubeform.dev/provider-equinixmetal-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BgpSessions returns a BgpSessionInformer.
	BgpSessions() BgpSessionInformer
	// Connections returns a ConnectionInformer.
	Connections() ConnectionInformer
	// Devices returns a DeviceInformer.
	Devices() DeviceInformer
	// DeviceNetworkTypes returns a DeviceNetworkTypeInformer.
	DeviceNetworkTypes() DeviceNetworkTypeInformer
	// IpAttachments returns a IpAttachmentInformer.
	IpAttachments() IpAttachmentInformer
	// Organizations returns a OrganizationInformer.
	Organizations() OrganizationInformer
	// PortVLANAttachments returns a PortVLANAttachmentInformer.
	PortVLANAttachments() PortVLANAttachmentInformer
	// Projects returns a ProjectInformer.
	Projects() ProjectInformer
	// ProjectAPIKeys returns a ProjectAPIKeyInformer.
	ProjectAPIKeys() ProjectAPIKeyInformer
	// ProjectSSHKeys returns a ProjectSSHKeyInformer.
	ProjectSSHKeys() ProjectSSHKeyInformer
	// ReservedIPBlocks returns a ReservedIPBlockInformer.
	ReservedIPBlocks() ReservedIPBlockInformer
	// SpotMarketRequests returns a SpotMarketRequestInformer.
	SpotMarketRequests() SpotMarketRequestInformer
	// SshKeys returns a SshKeyInformer.
	SshKeys() SshKeyInformer
	// UserAPIKeys returns a UserAPIKeyInformer.
	UserAPIKeys() UserAPIKeyInformer
	// VirtualCircuits returns a VirtualCircuitInformer.
	VirtualCircuits() VirtualCircuitInformer
	// Vlans returns a VlanInformer.
	Vlans() VlanInformer
	// Volumes returns a VolumeInformer.
	Volumes() VolumeInformer
	// VolumeAttachments returns a VolumeAttachmentInformer.
	VolumeAttachments() VolumeAttachmentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BgpSessions returns a BgpSessionInformer.
func (v *version) BgpSessions() BgpSessionInformer {
	return &bgpSessionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Connections returns a ConnectionInformer.
func (v *version) Connections() ConnectionInformer {
	return &connectionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Devices returns a DeviceInformer.
func (v *version) Devices() DeviceInformer {
	return &deviceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DeviceNetworkTypes returns a DeviceNetworkTypeInformer.
func (v *version) DeviceNetworkTypes() DeviceNetworkTypeInformer {
	return &deviceNetworkTypeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IpAttachments returns a IpAttachmentInformer.
func (v *version) IpAttachments() IpAttachmentInformer {
	return &ipAttachmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Organizations returns a OrganizationInformer.
func (v *version) Organizations() OrganizationInformer {
	return &organizationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PortVLANAttachments returns a PortVLANAttachmentInformer.
func (v *version) PortVLANAttachments() PortVLANAttachmentInformer {
	return &portVLANAttachmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Projects returns a ProjectInformer.
func (v *version) Projects() ProjectInformer {
	return &projectInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ProjectAPIKeys returns a ProjectAPIKeyInformer.
func (v *version) ProjectAPIKeys() ProjectAPIKeyInformer {
	return &projectAPIKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ProjectSSHKeys returns a ProjectSSHKeyInformer.
func (v *version) ProjectSSHKeys() ProjectSSHKeyInformer {
	return &projectSSHKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ReservedIPBlocks returns a ReservedIPBlockInformer.
func (v *version) ReservedIPBlocks() ReservedIPBlockInformer {
	return &reservedIPBlockInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SpotMarketRequests returns a SpotMarketRequestInformer.
func (v *version) SpotMarketRequests() SpotMarketRequestInformer {
	return &spotMarketRequestInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SshKeys returns a SshKeyInformer.
func (v *version) SshKeys() SshKeyInformer {
	return &sshKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UserAPIKeys returns a UserAPIKeyInformer.
func (v *version) UserAPIKeys() UserAPIKeyInformer {
	return &userAPIKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VirtualCircuits returns a VirtualCircuitInformer.
func (v *version) VirtualCircuits() VirtualCircuitInformer {
	return &virtualCircuitInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Vlans returns a VlanInformer.
func (v *version) Vlans() VlanInformer {
	return &vlanInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Volumes returns a VolumeInformer.
func (v *version) Volumes() VolumeInformer {
	return &volumeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeAttachments returns a VolumeAttachmentInformer.
func (v *version) VolumeAttachments() VolumeAttachmentInformer {
	return &volumeAttachmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
