apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: equinixmetal.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: connections.connection.equinixmetal.kubeform.com
spec:
  group: connection.equinixmetal.kubeform.com
  names:
    kind: Connection
    listKind: ConnectionList
    plural: connections
    singular: connection
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  description:
                    description: Description of the connection resource
                    type: string
                  facility:
                    description: Facility where the connection will be created
                    type: string
                  id:
                    type: string
                  metro:
                    description: Metro where the connection will be created
                    type: string
                  mode:
                    description: Mode for connections in IBX facilities with the dedicated
                      type - standard or tunnel
                    type: string
                  name:
                    description: Name of the connection resource
                    type: string
                  organizationID:
                    description: ID of the organization responsible for the connection
                      Deprecated
                    type: string
                  ports:
                    description: List of connection ports - primary (`ports[0]`) and
                      secondary (`ports[1]`)
                    items:
                      properties:
                        ID:
                          description: ID of the connection port resource
                          type: string
                        linkStatus:
                          description: Port link status
                          type: string
                        name:
                          description: Name of the connection port resource
                          type: string
                        role:
                          description: Role - primary or secondary
                          type: string
                        speed:
                          description: Port speed in bits per second
                          format: int64
                          type: integer
                        status:
                          description: Port status
                          type: string
                        virtualCircuitIDS:
                          additionalProperties:
                            type: string
                          description: List of IDs of virtual circuits attached to
                            this port
                          type: object
                      type: object
                    type: array
                  projectID:
                    description: ID of the project where the connection is scoped
                      to, only used for type == "shared"
                    type: string
                  redundancy:
                    description: Connection redundancy - redundant or primary
                    type: string
                  serviceTokenType:
                    description: Only used with shared connection. Type of service
                      token to use for the connection, a_side or z_side.
                    type: string
                  serviceTokens:
                    description: Only used with shared connection. List of service
                      tokens to use for the connection.
                    items:
                      properties:
                        ID:
                          description: ID of the service token
                          type: string
                        expiresAt:
                          description: Expiration date of the service token
                          type: string
                        maxAllowedSpeed:
                          description: Maximum allowed speed for the service token
                          type: string
                        role:
                          description: Role of the service token
                          type: string
                        state:
                          description: State of the service token
                          type: string
                        type:
                          description: Type of the service token, a_side or z_side
                          type: string
                      type: object
                    type: array
                  speed:
                    description: Port speed. Allowed values are 50Mbps, 200Mbps, 500Mbps,
                      1Gbps, 2Gbps, 5Gbps, 10Gbps
                    type: string
                  status:
                    description: Status of the connection resource
                    type: string
                  tags:
                    description: Tags attached to the connection
                    items:
                      type: string
                    type: array
                  token:
                    description: Fabric Token from the [Equinix Fabric Portal](https://ecxfabric.equinix.com/dashboard)
                      Deprecated
                    type: string
                  type:
                    description: Connection type - dedicated or shared
                    type: string
                  vlans:
                    description: Only used with shared connection. Vlans to attach.
                      Pass one vlan for Primary/Single connection and two vlans for
                      Redundant connection.
                    items:
                      format: int64
                      type: integer
                    maxItems: 2
                    type: array
                required:
                - name
                - projectID
                - redundancy
                - speed
                - type
                type: object
              state:
                properties:
                  description:
                    description: Description of the connection resource
                    type: string
                  facility:
                    description: Facility where the connection will be created
                    type: string
                  id:
                    type: string
                  metro:
                    description: Metro where the connection will be created
                    type: string
                  mode:
                    description: Mode for connections in IBX facilities with the dedicated
                      type - standard or tunnel
                    type: string
                  name:
                    description: Name of the connection resource
                    type: string
                  organizationID:
                    description: ID of the organization responsible for the connection
                      Deprecated
                    type: string
                  ports:
                    description: List of connection ports - primary (`ports[0]`) and
                      secondary (`ports[1]`)
                    items:
                      properties:
                        ID:
                          description: ID of the connection port resource
                          type: string
                        linkStatus:
                          description: Port link status
                          type: string
                        name:
                          description: Name of the connection port resource
                          type: string
                        role:
                          description: Role - primary or secondary
                          type: string
                        speed:
                          description: Port speed in bits per second
                          format: int64
                          type: integer
                        status:
                          description: Port status
                          type: string
                        virtualCircuitIDS:
                          additionalProperties:
                            type: string
                          description: List of IDs of virtual circuits attached to
                            this port
                          type: object
                      type: object
                    type: array
                  projectID:
                    description: ID of the project where the connection is scoped
                      to, only used for type == "shared"
                    type: string
                  redundancy:
                    description: Connection redundancy - redundant or primary
                    type: string
                  serviceTokenType:
                    description: Only used with shared connection. Type of service
                      token to use for the connection, a_side or z_side.
                    type: string
                  serviceTokens:
                    description: Only used with shared connection. List of service
                      tokens to use for the connection.
                    items:
                      properties:
                        ID:
                          description: ID of the service token
                          type: string
                        expiresAt:
                          description: Expiration date of the service token
                          type: string
                        maxAllowedSpeed:
                          description: Maximum allowed speed for the service token
                          type: string
                        role:
                          description: Role of the service token
                          type: string
                        state:
                          description: State of the service token
                          type: string
                        type:
                          description: Type of the service token, a_side or z_side
                          type: string
                      type: object
                    type: array
                  speed:
                    description: Port speed. Allowed values are 50Mbps, 200Mbps, 500Mbps,
                      1Gbps, 2Gbps, 5Gbps, 10Gbps
                    type: string
                  status:
                    description: Status of the connection resource
                    type: string
                  tags:
                    description: Tags attached to the connection
                    items:
                      type: string
                    type: array
                  token:
                    description: Fabric Token from the [Equinix Fabric Portal](https://ecxfabric.equinix.com/dashboard)
                      Deprecated
                    type: string
                  type:
                    description: Connection type - dedicated or shared
                    type: string
                  vlans:
                    description: Only used with shared connection. Vlans to attach.
                      Pass one vlan for Primary/Single connection and two vlans for
                      Redundant connection.
                    items:
                      format: int64
                      type: integer
                    maxItems: 2
                    type: array
                required:
                - name
                - projectID
                - redundancy
                - speed
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
