apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: equinixmetal.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: ports.port.equinixmetal.kubeform.com
spec:
  group: port.equinixmetal.kubeform.com
  names:
    kind: Port
    listKind: PortList
    plural: ports
    singular: port
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  bondID:
                    description: UUID of the bond port
                    type: string
                  bondName:
                    description: Name of the bond port
                    type: string
                  bonded:
                    description: Flag indicating whether the port should be bonded
                    type: boolean
                  disbondSupported:
                    description: Flag indicating whether the port can be removed from
                      a bond
                    type: boolean
                  id:
                    type: string
                  layer2:
                    description: Flag indicating whether the port is in layer2 (or
                      layer3) mode
                    type: boolean
                  mac:
                    description: MAC address of the port
                    type: string
                  name:
                    description: Name of the port to look up, e.g. bond0, eth1
                    type: string
                  nativeVLANID:
                    description: UUID of native VLAN of the port
                    type: string
                  networkType:
                    description: One of layer2-bonded, layer2-individual, layer3,
                      hybrid and hybrid-bonded. This attribute is only set on bond
                      ports.
                    type: string
                  portID:
                    description: UUID of the port to lookup
                    type: string
                  resetOnDelete:
                    description: Behavioral setting to reset the port to default settings.
                      For a bond port it means layer3 without vlans attached, eth
                      ports will be bonded without native vlan and vlans attached
                    type: boolean
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  type:
                    description: Port type
                    type: string
                  vlanIDS:
                    description: UUIDs VLANs to attach. To avoid jitter, use the UUID
                      and not the VXLAN
                    items:
                      type: string
                    type: array
                  vxlanIDS:
                    description: 'VLAN VXLAN ids to attach (example: [1000])'
                    items:
                      format: int64
                      type: integer
                    type: array
                required:
                - bonded
                - portID
                type: object
              state:
                properties:
                  bondID:
                    description: UUID of the bond port
                    type: string
                  bondName:
                    description: Name of the bond port
                    type: string
                  bonded:
                    description: Flag indicating whether the port should be bonded
                    type: boolean
                  disbondSupported:
                    description: Flag indicating whether the port can be removed from
                      a bond
                    type: boolean
                  id:
                    type: string
                  layer2:
                    description: Flag indicating whether the port is in layer2 (or
                      layer3) mode
                    type: boolean
                  mac:
                    description: MAC address of the port
                    type: string
                  name:
                    description: Name of the port to look up, e.g. bond0, eth1
                    type: string
                  nativeVLANID:
                    description: UUID of native VLAN of the port
                    type: string
                  networkType:
                    description: One of layer2-bonded, layer2-individual, layer3,
                      hybrid and hybrid-bonded. This attribute is only set on bond
                      ports.
                    type: string
                  portID:
                    description: UUID of the port to lookup
                    type: string
                  resetOnDelete:
                    description: Behavioral setting to reset the port to default settings.
                      For a bond port it means layer3 without vlans attached, eth
                      ports will be bonded without native vlan and vlans attached
                    type: boolean
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  type:
                    description: Port type
                    type: string
                  vlanIDS:
                    description: UUIDs VLANs to attach. To avoid jitter, use the UUID
                      and not the VXLAN
                    items:
                      type: string
                    type: array
                  vxlanIDS:
                    description: 'VLAN VXLAN ids to attach (example: [1000])'
                    items:
                      format: int64
                      type: integer
                    type: array
                required:
                - bonded
                - portID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
