apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: equinixmetal.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: ipblocks.reserved.equinixmetal.kubeform.com
spec:
  group: reserved.equinixmetal.kubeform.com
  names:
    kind: IpBlock
    listKind: IpBlockList
    plural: ipblocks
    singular: ipblock
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  address:
                    type: string
                  addressFamily:
                    description: Address family as integer (4 or 6)
                    format: int64
                    type: integer
                  cidr:
                    description: Length of CIDR prefix of the block as integer
                    format: int64
                    type: integer
                  cidrNotation:
                    type: string
                  description:
                    description: Arbitrary description
                    type: string
                  facility:
                    description: Facility where to allocate the public IP address
                      block, makes sense only for type==public_ipv4, must be empty
                      for type==global_ipv4, conflicts with metro
                    type: string
                  gateway:
                    type: string
                  global:
                    description: Flag indicating whether IP block is global, i.e.
                      assignable in any location
                    type: boolean
                  id:
                    type: string
                  manageable:
                    type: boolean
                  management:
                    type: boolean
                  metro:
                    description: Metro where to allocate the public IP address block,
                      makes sense only for type==public_ipv4, must be empty for type==global_ipv4,
                      conflicts with facility
                    type: string
                  netmask:
                    description: Mask in decimal notation, e.g. 255.255.255.0
                    type: string
                  network:
                    description: Network IP address portion of the block specification
                    type: string
                  projectID:
                    description: The metal project ID where to allocate the address
                      block
                    type: string
                  public:
                    description: Flag indicating whether IP block is addressable from
                      the Internet
                    type: boolean
                  quantity:
                    description: The number of allocated /32 addresses, a power of
                      2
                    format: int64
                    type: integer
                  tags:
                    description: Tags attached to the reserved block
                    items:
                      type: string
                    type: array
                  type:
                    description: Either global_ipv4 or public_ipv4, defaults to public_ipv4
                      for backward compatibility
                    type: string
                required:
                - projectID
                - quantity
                type: object
              state:
                properties:
                  address:
                    type: string
                  addressFamily:
                    description: Address family as integer (4 or 6)
                    format: int64
                    type: integer
                  cidr:
                    description: Length of CIDR prefix of the block as integer
                    format: int64
                    type: integer
                  cidrNotation:
                    type: string
                  description:
                    description: Arbitrary description
                    type: string
                  facility:
                    description: Facility where to allocate the public IP address
                      block, makes sense only for type==public_ipv4, must be empty
                      for type==global_ipv4, conflicts with metro
                    type: string
                  gateway:
                    type: string
                  global:
                    description: Flag indicating whether IP block is global, i.e.
                      assignable in any location
                    type: boolean
                  id:
                    type: string
                  manageable:
                    type: boolean
                  management:
                    type: boolean
                  metro:
                    description: Metro where to allocate the public IP address block,
                      makes sense only for type==public_ipv4, must be empty for type==global_ipv4,
                      conflicts with facility
                    type: string
                  netmask:
                    description: Mask in decimal notation, e.g. 255.255.255.0
                    type: string
                  network:
                    description: Network IP address portion of the block specification
                    type: string
                  projectID:
                    description: The metal project ID where to allocate the address
                      block
                    type: string
                  public:
                    description: Flag indicating whether IP block is addressable from
                      the Internet
                    type: boolean
                  quantity:
                    description: The number of allocated /32 addresses, a power of
                      2
                    format: int64
                    type: integer
                  tags:
                    description: Tags attached to the reserved block
                    items:
                      type: string
                    type: array
                  type:
                    description: Either global_ipv4 or public_ipv4, defaults to public_ipv4
                      for backward compatibility
                    type: string
                required:
                - projectID
                - quantity
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
