/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-equinixmetal-api/apis/device/v1alpha1"
	scheme "kubeform.dev/provider-equinixmetal-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkTypesGetter has a method to return a NetworkTypeInterface.
// A group's client should implement this interface.
type NetworkTypesGetter interface {
	NetworkTypes(namespace string) NetworkTypeInterface
}

// NetworkTypeInterface has methods to work with NetworkType resources.
type NetworkTypeInterface interface {
	Create(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.CreateOptions) (*v1alpha1.NetworkType, error)
	Update(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.UpdateOptions) (*v1alpha1.NetworkType, error)
	UpdateStatus(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.UpdateOptions) (*v1alpha1.NetworkType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkType, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkType, err error)
	NetworkTypeExpansion
}

// networkTypes implements NetworkTypeInterface
type networkTypes struct {
	client rest.Interface
	ns     string
}

// newNetworkTypes returns a NetworkTypes
func newNetworkTypes(c *DeviceV1alpha1Client, namespace string) *networkTypes {
	return &networkTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkType, and returns the corresponding networkType object, and an error if there is any.
func (c *networkTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkType, err error) {
	result = &v1alpha1.NetworkType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networktypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkTypes that match those selectors.
func (c *networkTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networktypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkTypes.
func (c *networkTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networktypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkType and creates it.  Returns the server's representation of the networkType, and an error, if there is any.
func (c *networkTypes) Create(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.CreateOptions) (result *v1alpha1.NetworkType, err error) {
	result = &v1alpha1.NetworkType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networktypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkType and updates it. Returns the server's representation of the networkType, and an error, if there is any.
func (c *networkTypes) Update(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.UpdateOptions) (result *v1alpha1.NetworkType, err error) {
	result = &v1alpha1.NetworkType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networktypes").
		Name(networkType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *networkTypes) UpdateStatus(ctx context.Context, networkType *v1alpha1.NetworkType, opts v1.UpdateOptions) (result *v1alpha1.NetworkType, err error) {
	result = &v1alpha1.NetworkType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networktypes").
		Name(networkType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkType and deletes it. Returns an error if one occurs.
func (c *networkTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networktypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networktypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkType.
func (c *networkTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkType, err error) {
	result = &v1alpha1.NetworkType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networktypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
